Repository AY2122S2-CS2103T-T09-3/tp, pull requests merged in 2022-03, with the labels that each got.

#60 Modify AB3 Model Components
  src/main/java/seedu/address/model/ModelManagerTrackermon.java
  src/main/java/seedu/address/model/ModelTrackermon.java
  src/main/java/seedu/address/model/ReadOnlyShowList.java
  src/main/java/seedu/address/model/ReadOnlyUserPrefsTrackermon.java
  src/main/java/seedu/address/model/ShowList.java
  src/main/java/seedu/address/model/UserPrefsTrackermon.java
  src/main/java/seedu/address/model/show/Name.java
  src/main/java/seedu/address/model/show/Show.java
  src/main/java/seedu/address/model/show/Status.java
  src/main/java/seedu/address/model/show/UniqueShowList.java
  src/main/java/seedu/address/model/show/exceptions/DuplicatedShowException.java
  src/main/java/seedu/address/model/show/exceptions/ShowNotFoundException.java
Labels: type.Task, priority.High

#61 Modify AB3 Logic (Commands)
  src/main/java/seedu/address/commons/core/MessagesTrackermon.java
  src/main/java/seedu/address/logic/commands/AddCommandTrackermon.java
  src/main/java/seedu/address/logic/commands/CommandResultTrackermon.java
  src/main/java/seedu/address/logic/commands/CommandTrackermon.java
  src/main/java/seedu/address/logic/commands/DeleteCommandTrackermon.java
  src/main/java/seedu/address/logic/commands/ExitCommandTrackermon.java
  src/main/java/seedu/address/logic/commands/HelpCommandTrackermon.java
  src/main/java/seedu/address/logic/commands/ListCommandTrackermon.java
  src/main/java/seedu/address/logic/commands/exceptions/CommandException.java
  src/main/java/seedu/address/logic/parser/CliSyntaxTrackermon.java
Labels: type.Task, priority.High

#65 Modify UI components
  src/main/java/seedu/address/ui/ShowCard.java
  src/main/java/seedu/address/ui/ShowListPanel.java
Labels: type.Task, priority.High

#84 Update Help UI - URL link
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: type.Task, priority.High

#81 Update Developer Guide - Architecture and Logic
  docs/DeveloperGuide.md
  docs/images/ArchitectureSequenceDiagram.png
  docs/images/DeleteSequenceDiagram.png
  docs/images/LogicClassDiagram.png
  docs/images/ParserClasses.png
Labels: type.Task, priority.High

#83 Update DG - UI UML diagram and information
  docs/DeveloperGuide.md
  docs/images/UiClassDiagram.png
Labels: type.Task, priority.High

#82 Test Show and UniqueShowList Class
  src/main/java/seedu/address/model/show/Show.java
  src/main/java/seedu/address/model/show/Status.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/TempCommandTestUtil.java
  src/test/java/seedu/address/model/show/NameTest.java
  src/test/java/seedu/address/model/show/ShowTest.java
  src/test/java/seedu/address/model/show/UniqueShowListTest.java
  src/test/java/seedu/address/testutil/ShowBuilder.java
  src/test/java/seedu/address/testutil/TypicalShows.java
Labels: type.Task, priority.Medium

#85 Modify Find Command and Update UG - Find and Help
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/TrackermonParser.java
  src/main/java/seedu/address/model/show/NameContainsKeywordsPredicate.java
Labels: type.Task, priority.Medium

#92 Update UML diagrams for Architecture, Logic and UI
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/LogicClassDiagram.puml
  docs/diagrams/ParserClasses.puml
  docs/diagrams/UiClassDiagram.puml
  docs/images/ArchitectureSequenceDiagram.png
  docs/images/DeleteSequenceDiagram.png
  docs/images/LogicClassDiagram.png
  docs/images/ParserClasses.png
  docs/images/UiClassDiagram.png
Labels: type.Task, priority.High

#93 Update User Guide - Table of Contents, Minor Issues, Return to top
  docs/UserGuide.md
  docs/images/toc-icon.png
Labels: type.Task, priority.High

#94 QuickFix - UG minor fix
  docs/UserGuide.md
Labels: type.Task, priority.High

#95 Update AboutUs
  docs/AboutUs.md
Labels: type.Task, priority.High

#96 Update UG - Table of Contents
  docs/UserGuide.md
Labels: type.Task, priority.High

#98 Update DG's formatting
  docs/DeveloperGuide.md
Labels: type.Task, priority.High

#99 Update AboutUs information
  docs/AboutUs.md
Labels: type.Task, priority.High

#100 Modify BetterModelClassDiagram.puml and BetterModelClassDiagram.png
  docs/diagrams/BetterModelClassDiagram.puml
  docs/images/BetterModelClassDiagram.png
Labels: type.Task, priority.High

#102 Implement Edit Feature
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/tracing/LogicSequenceDiagram.puml
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/TrackermonParser.java
Labels: type.Task, priority.High

#105 Update DG, UG, and EditCommand
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/EditCommand.java
Labels: type.Task, priority.High

#107 Update Build Gradle Name
  build.gradle
Labels: type.Task, priority.High

#111 Update UG
  docs/UserGuide.md
Labels: type.Task, priority.High

#110 Edit Trackermon's data file's name
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/MainWindowTrackermon.fxml
  src/main/resources/view/PersonListCard.fxml
  src/main/resources/view/PersonListPanel.fxml
  src/test/data/JsonUserPrefsStorageTest/ExtraValuesUserPref.json
  src/test/data/JsonUserPrefsStorageTest/TypicalUserPref.json
Labels: type.Bug, priority.High

#115 Update Developer Guide (User Stories, Saving Data)
  docs/DeveloperGuide.md
Labels: type.Task, priority.High

#116 Fix typo in DG
  docs/DeveloperGuide.md
  docs/images/BetterModelClassDiagram.png
Labels: type.Task, priority.High

#108 Test logic parser
  src/test/java/seedu/trackermon/logic/LogicManagerTest.java
  src/test/java/seedu/trackermon/logic/commands/CommandTestUtil.java
  src/test/java/seedu/trackermon/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/trackermon/logic/parser/CommandParserTestUtil.java
  src/test/java/seedu/trackermon/logic/parser/DeleteCommandParserTest.java
  src/test/java/seedu/trackermon/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/trackermon/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/trackermon/logic/parser/ParserUtilTest.java
  src/test/java/seedu/trackermon/logic/parser/TrackermonParserTest.java
  src/test/java/seedu/trackermon/testutil/EditShowDescriptorBuilder.java
  src/test/java/seedu/trackermon/testutil/ShowUtil.java
  src/test/java/seedu/trackermon/testutil/TestUtil.java
  src/test/java/seedu/trackermon/testutil/TypicalIndexes.java
Labels: type.Task, priority.High

#127 Update Test Logic Commands
  src/main/java/seedu/trackermon/logic/commands/AddCommand.java
  src/main/java/seedu/trackermon/model/ModelManager.java
  src/main/java/seedu/trackermon/model/ReadOnlyShowList.java
  src/main/java/seedu/trackermon/model/ShowList.java
  src/main/java/seedu/trackermon/storage/JsonSerializableShowList.java
  src/main/java/seedu/trackermon/storage/ShowListStorage.java
  src/main/java/seedu/trackermon/ui/UiPart.java
  src/test/java/seedu/trackermon/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/trackermon/logic/commands/AddCommandTest.java
  src/test/java/seedu/trackermon/logic/commands/CommandTestUtil.java
  src/test/java/seedu/trackermon/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/trackermon/logic/commands/EditCommandTest.java
  src/test/java/seedu/trackermon/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/trackermon/logic/commands/EditShowDescriptorTest.java
  src/test/java/seedu/trackermon/logic/commands/ExitCommandTest.java
  src/test/java/seedu/trackermon/logic/commands/FindCommandTest.java
  src/test/java/seedu/trackermon/logic/commands/HelpCommandTest.java
  src/test/java/seedu/trackermon/logic/commands/ListCommandTest.java
  src/test/java/seedu/trackermon/model/show/ShowTest.java
  src/test/java/seedu/trackermon/model/show/UniqueShowListTest.java
  src/test/java/seedu/trackermon/storage/JsonSerializableAddressBookTest.java
  src/test/java/seedu/trackermon/testutil/TypicalShows.java
Labels: type.Task, priority.High

#132 Update Help Window
  src/main/java/seedu/trackermon/MainApp.java
  src/main/java/seedu/trackermon/ui/CommandBuilder.java
  src/main/java/seedu/trackermon/ui/HelpWindow.java
  src/main/resources/view/HelpWindow.fxml
Labels: type.Task, priority.High

#129 Add Sort Functionality
  src/main/java/seedu/trackermon/logic/Logic.java
  src/main/java/seedu/trackermon/logic/LogicManager.java
  src/main/java/seedu/trackermon/logic/commands/DeleteCommand.java
  src/main/java/seedu/trackermon/logic/commands/SortCommand.java
  src/main/java/seedu/trackermon/logic/parser/CliSyntax.java
  src/main/java/seedu/trackermon/logic/parser/SortCommandParser.java
  src/main/java/seedu/trackermon/logic/parser/TrackermonParser.java
  src/main/java/seedu/trackermon/model/Model.java
  src/main/java/seedu/trackermon/model/ModelManager.java
  src/main/java/seedu/trackermon/model/show/Name.java
  src/main/java/seedu/trackermon/model/show/NameComparator.java
  src/main/java/seedu/trackermon/model/show/Show.java
  src/main/java/seedu/trackermon/model/show/Status.java
  src/main/java/seedu/trackermon/model/show/StatusComparator.java
  src/main/java/seedu/trackermon/storage/JsonSerializableShowList.java
  src/main/java/seedu/trackermon/ui/MainWindow.java
  src/test/java/seedu/trackermon/logic/commands/AddCommandTest.java
Labels: type.Task, priority.High

#136 Remove saving after sort
  src/main/java/seedu/trackermon/model/Model.java
  src/main/java/seedu/trackermon/model/ModelManager.java
  src/test/java/seedu/trackermon/logic/commands/AddCommandTest.java
Labels: type.Bug, priority.High, severity.High

#130 Update GUI
  src/main/java/seedu/trackermon/logic/commands/CommandResult.java
  src/main/java/seedu/trackermon/logic/commands/ExitCommand.java
  src/main/java/seedu/trackermon/logic/commands/FindCommand.java
  src/main/java/seedu/trackermon/logic/commands/HelpCommand.java
  src/main/java/seedu/trackermon/logic/commands/ListCommand.java
  src/main/java/seedu/trackermon/ui/MainWindow.java
  src/main/java/seedu/trackermon/ui/ShowCard.java
  src/main/java/seedu/trackermon/ui/ShowDetailsCard.java
  src/main/java/seedu/trackermon/ui/ShowListPanel.java
  src/main/resources/view/CommandBox.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/ResultDisplay.fxml
  src/main/resources/view/ShowDetailsCard.fxml
  src/main/resources/view/ShowListCard.fxml
  src/test/java/seedu/trackermon/logic/commands/CommandResultTest.java
  src/test/java/seedu/trackermon/logic/commands/ExitCommandTest.java
  src/test/java/seedu/trackermon/logic/commands/HelpCommandTest.java
Labels: type.Task, priority.High

#138 Fix Bug for Find
  docs/DeveloperGuide.md
  src/main/java/seedu/trackermon/logic/commands/FindCommand.java
  src/main/java/seedu/trackermon/logic/parser/FindCommandParser.java
Labels: type.Bug, priority.High, severity.High

#133 Add Comment feature
  src/main/java/seedu/trackermon/logic/commands/AddCommand.java
  src/main/java/seedu/trackermon/logic/commands/CommentCommand.java
  src/main/java/seedu/trackermon/logic/commands/EditCommand.java
  src/main/java/seedu/trackermon/logic/parser/AddCommandParser.java
  src/main/java/seedu/trackermon/logic/parser/CliSyntax.java
  src/main/java/seedu/trackermon/logic/parser/CommentCommandParser.java
  src/main/java/seedu/trackermon/logic/parser/EditCommandParser.java
  src/main/java/seedu/trackermon/logic/parser/ParserUtil.java
  src/main/java/seedu/trackermon/logic/parser/TrackermonParser.java
  src/main/java/seedu/trackermon/model/show/Comment.java
  src/main/java/seedu/trackermon/model/show/Show.java
  src/main/java/seedu/trackermon/model/util/SampleDataUtil.java
  src/main/java/seedu/trackermon/storage/JsonAdaptedShow.java
  src/test/java/seedu/trackermon/logic/LogicManagerTest.java
  src/test/java/seedu/trackermon/logic/commands/CommandTestUtil.java
  src/test/java/seedu/trackermon/logic/commands/EditCommandTest.java
  src/test/java/seedu/trackermon/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/trackermon/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/trackermon/testutil/EditShowDescriptorBuilder.java
  src/test/java/seedu/trackermon/testutil/ShowBuilder.java
  src/test/java/seedu/trackermon/testutil/ShowUtil.java
  src/test/java/seedu/trackermon/testutil/TypicalShows.java
Labels: type.Task, priority.High

#141 Enable Assertions
  build.gradle
Labels: type.Task, priority.High

#140 Update UG and DG for sort
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/SortSequenceDiagram.puml
  docs/diagrams/SortShowDiagram.puml
  docs/images/SortSequenceDiagram.png
  docs/images/SortShowDiagram.png
Labels: type.Task, priority.High

#146 Fix bug not adding to last index, issue #144
  src/main/java/seedu/trackermon/model/Model.java
Labels: type.Bug

#147 Add clear function
  src/main/java/seedu/trackermon/logic/commands/ClearCommand.java
  src/main/java/seedu/trackermon/logic/parser/TrackermonParser.java
Labels: type.Task

#151 Fix UI issues
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/trackermon/logic/commands/CommandResult.java
  src/main/java/seedu/trackermon/logic/commands/ExitCommand.java
  src/main/java/seedu/trackermon/logic/commands/FindCommand.java
  src/main/java/seedu/trackermon/logic/commands/HelpCommand.java
  src/main/java/seedu/trackermon/logic/commands/ListCommand.java
  src/main/java/seedu/trackermon/ui/MainWindow.java
  src/main/java/seedu/trackermon/ui/ShowDetailsCard.java
  src/main/java/seedu/trackermon/ui/ShowListPanel.java
  src/test/java/seedu/trackermon/logic/commands/CommandResultTest.java
  src/test/java/seedu/trackermon/logic/commands/ExitCommandTest.java
  src/test/java/seedu/trackermon/logic/commands/HelpCommandTest.java
Labels: type.Task, type.Bug, priority.Medium

#150 Update UI UML Diagram and Format manual testing section
  docs/DeveloperGuide.md
  docs/diagrams/UiClassDiagram.puml
  docs/images/UiClassDiagram.png
  src/main/java/seedu/trackermon/ui/ShowDetailsCard.java
Labels: type.Task, priority.High

#149 Update Developer Guide (Comment Command)
  docs/DeveloperGuide.md
  docs/diagrams/ModelClassDiagram.puml
  docs/images/ModelClassDiagram.png
Labels: type.Task, priority.High

#155 Add Import and Export feature, DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/trackermon/logic/LogicManager.java
  src/main/java/seedu/trackermon/logic/commands/CommandResult.java
  src/main/java/seedu/trackermon/logic/commands/ExportCommand.java
  src/main/java/seedu/trackermon/logic/commands/ImportCommand.java
  src/main/java/seedu/trackermon/logic/parser/TrackermonParser.java
  src/test/java/seedu/trackermon/logic/LogicManagerTest.java
Labels: type.Task, priority.High

#158 Fix checkstyle errors
  src/main/java/seedu/trackermon/logic/commands/ExportCommand.java
  src/main/java/seedu/trackermon/logic/commands/ImportCommand.java
Labels: type.Task, priority.High

#160 Update Import and Export Implementation, DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/trackermon/logic/LogicManager.java
  src/main/java/seedu/trackermon/logic/commands/ExportCommand.java
  src/main/java/seedu/trackermon/logic/commands/ImportCommand.java
  src/main/java/seedu/trackermon/storage/JsonFileManager.java
Labels: type.Task, priority.High

#161 Fix heading issue in DG
  docs/DeveloperGuide.md
Labels: priority.High, severity.VeryLow

#162 Fix Import and Export crashes and Add support for macos
  src/main/java/seedu/trackermon/logic/commands/ExportCommand.java
  src/main/java/seedu/trackermon/logic/commands/ImportCommand.java
  src/main/java/seedu/trackermon/storage/JsonFileManager.java
  src/main/resources/view/ResultDisplay.fxml
Labels: type.Task, type.Bug, priority.High

#165 Add GUI for comment
  src/main/java/seedu/trackermon/model/show/Status.java
  src/main/java/seedu/trackermon/ui/HelpWindow.java
  src/main/java/seedu/trackermon/ui/MainWindow.java
  src/main/java/seedu/trackermon/ui/ShowCard.java
  src/main/java/seedu/trackermon/ui/ShowDetailsCard.java
  src/main/resources/view/CommandBox.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/ShowDetailsCard.fxml
Labels: type.Task, priority.High

#166 Update UG
  docs/UserGuide.md
  src/main/java/seedu/trackermon/ui/HelpWindow.java
  src/main/resources/view/HelpWindow.fxml
Labels: type.Task, priority.High

#164 Update DG
  docs/DeveloperGuide.md
  docs/_sass/minima/_base.scss
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/FindSequenceDiagram.puml
  docs/diagrams/FindSequenceReferenceDiagram.puml
  docs/images/BetterModelClassDiagram.png
  docs/images/FindSequenceDiagram.png
  docs/images/FindSequenceReferenceDiagram.png
Labels: type.Task, priority.High

#167 Fix Storage issues with mac and linux
  src/main/java/seedu/trackermon/MainApp.java
  src/main/java/seedu/trackermon/commons/core/Config.java
  src/main/java/seedu/trackermon/commons/core/JarTools.java
  src/main/java/seedu/trackermon/commons/core/LogsCenter.java
  src/main/java/seedu/trackermon/commons/util/FileUtil.java
  src/main/java/seedu/trackermon/logic/parser/CommentCommandParser.java
  src/main/java/seedu/trackermon/model/UserPrefs.java
  src/main/java/seedu/trackermon/ui/CommandBuilder.java
Labels: type.Task, type.Bug, priority.High

#174 Fix Sort, Edit and Showlist issue Bug
  src/main/java/seedu/trackermon/logic/commands/DeleteCommand.java
  src/main/java/seedu/trackermon/logic/commands/EditCommand.java
  src/main/java/seedu/trackermon/model/Model.java
  src/main/java/seedu/trackermon/model/ModelManager.java
  src/main/java/seedu/trackermon/ui/MainWindow.java
  src/test/java/seedu/trackermon/logic/commands/AddCommandTest.java
  src/test/java/seedu/trackermon/logic/commands/EditCommandTest.java
Labels: type.Bug, priority.High, severity.High

#175 Add Rating Feature
  src/main/java/seedu/trackermon/logic/commands/AddCommand.java
  src/main/java/seedu/trackermon/logic/commands/CommentCommand.java
  src/main/java/seedu/trackermon/logic/commands/EditCommand.java
  src/main/java/seedu/trackermon/logic/parser/AddCommandParser.java
  src/main/java/seedu/trackermon/logic/parser/CliSyntax.java
  src/main/java/seedu/trackermon/logic/parser/EditCommandParser.java
  src/main/java/seedu/trackermon/logic/parser/ParserUtil.java
  src/main/java/seedu/trackermon/model/show/Rating.java
  src/main/java/seedu/trackermon/model/show/Show.java
  src/main/java/seedu/trackermon/model/show/exceptions/RatingNotValidException.java
  src/main/java/seedu/trackermon/model/util/SampleDataUtil.java
  src/main/java/seedu/trackermon/storage/JsonAdaptedShow.java
  src/test/java/seedu/trackermon/logic/LogicManagerTest.java
  src/test/java/seedu/trackermon/logic/commands/CommandTestUtil.java
  src/test/java/seedu/trackermon/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/trackermon/testutil/EditShowDescriptorBuilder.java
  src/test/java/seedu/trackermon/testutil/ShowBuilder.java
  src/test/java/seedu/trackermon/testutil/ShowUtil.java
  src/test/java/seedu/trackermon/testutil/TypicalShows.java
Labels: type.Story, priority.High

#172 Add Quality of Life feature for Add, Edit and Comment
  src/main/java/seedu/trackermon/logic/commands/AddCommand.java
  src/main/java/seedu/trackermon/logic/commands/CommandResult.java
  src/main/java/seedu/trackermon/logic/commands/CommentCommand.java
  src/main/java/seedu/trackermon/logic/commands/EditCommand.java
  src/main/java/seedu/trackermon/model/Model.java
  src/main/java/seedu/trackermon/model/ModelManager.java
  src/main/java/seedu/trackermon/ui/MainWindow.java
  src/main/java/seedu/trackermon/ui/ShowCard.java
  src/main/java/seedu/trackermon/ui/ShowDetailsCard.java
  src/main/java/seedu/trackermon/ui/ShowListPanel.java
  src/main/resources/images/icon_star.png
  src/main/resources/images/icon_star_30.png
  src/main/resources/images/icon_star_filled.png
  src/main/resources/images/icon_star_filled_30.png
  src/main/resources/images/png2svg.zip
  src/main/resources/view/ShowDetailsCard.fxml
  src/main/resources/view/ShowListCard.fxml
  src/test/java/seedu/trackermon/logic/commands/AddCommandTest.java
Labels: type.Task, priority.Medium

#153 Update User Guide (Comment Command)
  docs/UserGuide.md
Labels: type.Task, priority.High

#176 Update Find feature to include Rating
  src/main/java/seedu/trackermon/logic/commands/FindCommand.java
  src/main/java/seedu/trackermon/logic/parser/FindCommandParser.java
  src/main/java/seedu/trackermon/model/show/RatingContainsKeywordsPredicate.java
  src/main/java/seedu/trackermon/model/show/ShowContainsKeywordsPredicate.java
  src/main/java/seedu/trackermon/model/show/StatusContainsKeywordsPredicate.java
  src/main/java/seedu/trackermon/model/show/TagsContainsKeywordsPredicate.java
Labels: type.Task, priority.High

#177 Fix storage bug on intellij
  src/main/java/seedu/trackermon/commons/core/Config.java
  src/main/java/seedu/trackermon/commons/core/JarTools.java
  src/main/java/seedu/trackermon/commons/core/LogsCenter.java
  src/main/java/seedu/trackermon/model/UserPrefs.java
Labels: type.Bug, priority.High, severity.Medium

#170 Add GUI for Rating and Minor restructure of userPrefFilePath
  src/main/java/seedu/trackermon/commons/core/Config.java
  src/main/java/seedu/trackermon/ui/ShowCard.java
  src/main/java/seedu/trackermon/ui/ShowDetailsCard.java
Labels: type.Task, priority.High

#181 Change font and colour to make it more readable
  src/main/java/seedu/trackermon/ui/CommandBox.java
  src/main/resources/view/DarkTheme.css
Labels: type.Task, priority.Medium

#180 Update UserGuide to include Rating
  docs/UserGuide.md
Labels: priority.High

#182 Rework sort
  src/main/java/seedu/trackermon/logic/commands/AddCommand.java
  src/main/java/seedu/trackermon/logic/commands/SortCommand.java
  src/main/java/seedu/trackermon/logic/parser/CliSyntax.java
  src/main/java/seedu/trackermon/logic/parser/SortCommandParser.java
  src/main/java/seedu/trackermon/model/show/Rating.java
  src/main/java/seedu/trackermon/model/show/RatingComparator.java
  src/main/java/seedu/trackermon/model/show/Show.java
  src/main/java/seedu/trackermon/model/show/TagComparator.java
  src/test/java/seedu/trackermon/logic/commands/AddCommandTest.java
Labels: type.Task, priority.High, severity.High

#184 Update UG after CS2101 Review
  docs/UserGuide.md
  docs/images/General_Find_UI.png
  docs/images/Precise_Find_UI.png
  docs/images/Precise_Find_UI_2.png
  docs/images/Trackermon_UI_Info.png
Labels: type.Task, priority.High

#188 Update Find test commands and Result Display
  src/main/java/seedu/trackermon/model/show/Show.java
  src/test/java/seedu/trackermon/logic/commands/FindCommandTest.java
  src/test/java/seedu/trackermon/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/trackermon/testutil/TypicalShows.java
Labels: type.Task, priority.Medium

#187 Make fields in Sort compulsory
  src/main/java/seedu/trackermon/logic/parser/ParserUtil.java
  src/main/java/seedu/trackermon/logic/parser/SortCommandParser.java
  src/main/java/seedu/trackermon/model/show/Name.java
Labels: type.Task, priority.High, severity.High

#185 Feature Suggest
  src/main/java/seedu/trackermon/logic/commands/SuggestCommand.java
  src/main/java/seedu/trackermon/logic/parser/TrackermonParser.java
  src/main/java/seedu/trackermon/model/show/SuggestPredicate.java
Labels: priority.Medium

#191 Update Help Window
  src/main/java/seedu/trackermon/ui/HelpWindow.java
  src/main/resources/view/HelpWindow.fxml
Labels: type.Task, priority.High

#198 Update UG to include images
  docs/UserGuide.md
  docs/images/AddImage.png
  docs/images/DeleteImage.png
  docs/images/EditImage.png
  docs/images/HelpWindow.png
  src/main/resources/view/HelpWindow.css
Labels: type.Task, priority.High

#197 Update UG for Export/Import, FAQ, Quick Start
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/Export.png
  docs/images/Import.png
Labels: type.Task, priority.High

#200 Update DG for import/export command and Fix bug for import
  docs/DeveloperGuide.md
  docs/diagrams/ExportSequenceDiagram.puml
  docs/diagrams/ImportSequenceDiagram.puml
  docs/images/ExportSequenceDiagram.png
  docs/images/ImportSequenceDiagram.png
  src/main/java/seedu/trackermon/logic/LogicManager.java
  src/main/java/seedu/trackermon/logic/commands/ExportCommand.java
  src/main/java/seedu/trackermon/logic/commands/ImportCommand.java
Labels: type.Task, type.Bug, priority.High

#202 Fix Sort and Suggest UG formatting
  docs/UserGuide.md
  docs/images/Sort_UI.png
  docs/images/Sort_UI2.png
  docs/images/Sort_UI3.png
  docs/images/SuggestImage.png
  src/main/java/seedu/trackermon/logic/parser/SortCommandParser.java
Labels: type.Task, priority.High

#203 Update UG for Find Command
  docs/UserGuide.md
Labels: priority.High
