Repository AY2122S2-CS2103T-T09-3/tp, pull requests merged in 2022-04, with the labels that each got.

#249 Fix edit spacing message, issue #207
  src/main/java/seedu/trackermon/logic/commands/EditCommand.java
Labels: priority.High, severity.High

#252 Add some tests and Change font from roboto back to Segoe UI
  src/main/java/seedu/trackermon/ui/ShowDetailsCard.java
  src/main/resources/view/DarkTheme.css
  src/test/java/seedu/trackermon/commons/core/ConfigTest.java
  src/test/java/seedu/trackermon/commons/core/GuiSettingsTest.java
  src/test/java/seedu/trackermon/commons/core/JarToolsTest.java
  src/test/java/seedu/trackermon/logic/LogicManagerTest.java
  src/test/java/seedu/trackermon/model/show/NameTest.java
  src/test/java/seedu/trackermon/model/show/ShowTest.java
  src/test/java/seedu/trackermon/ui/CommandBuilderTest.java
Labels: type.Task, priority.High

#251 Update PPP
  docs/DeveloperGuide.md
  docs/team/ardentsoul.md
Labels: type.Task, priority.High

#253 Bug fix edit order
  src/main/java/seedu/trackermon/logic/commands/AddCommand.java
  src/main/java/seedu/trackermon/model/Model.java
  src/main/java/seedu/trackermon/model/ModelManager.java
  src/test/java/seedu/trackermon/logic/commands/AddCommandTest.java
Labels: type.Bug, priority.High, severity.High

#250 Fix bugs after PE-D
  docs/UserGuide.md
  src/main/java/seedu/trackermon/logic/commands/FindCommand.java
  src/main/java/seedu/trackermon/logic/parser/FindCommandParser.java
  src/main/java/seedu/trackermon/model/show/Rating.java
Labels: priority.High, severity.Medium

#254 Update ppp
  docs/team/arcornior.md
  docs/team/ardentsoul.md
  docs/team/aweijun.md
  docs/team/johndoe.md
  docs/team/jonathanhoshi.md
  docs/team/lowkaiwei98.md
Labels: type.Task, priority.High, severity.High

#258 Reformat UG
  docs/UserGuide.md
  docs/images/EditTagExample.png
  src/main/resources/view/MainWindow.fxml
Labels: type.Task, priority.High

#257 Update DG
  docs/DevOps.md
  docs/DeveloperGuide.md
  docs/diagrams/UiClassDiagram.puml
  docs/images/UiClassDiagram.png
  docs/team/ardentsoul.md
Labels: type.Task, priority.High

#261 Fix Bug Rating
  src/main/java/seedu/trackermon/model/show/Rating.java
Labels: type.Bug, priority.Low

#260 [Bug] Suggest Command
  src/main/java/seedu/trackermon/logic/commands/SuggestCommand.java
Labels: type.Bug, priority.High

#262 Fix Bug (Add Command Error Message)
  src/main/java/seedu/trackermon/logic/commands/AddCommand.java
Labels: type.Bug, priority.Low

#259 Vet UG and Update Help Window
  docs/UserGuide.md
  docs/images/AddImage.png
  docs/images/DeleteImage.png
  docs/images/EditImage.png
  docs/images/General_Find_UI.png
  docs/images/HelpWindow.png
  docs/images/Precise_Find_UI.png
  docs/images/Precise_Find_UI_2.png
  docs/images/SuggestImage.png
  src/main/java/seedu/trackermon/ui/HelpWindow.java
Labels: type.Task, priority.High

#264 Limit Tag Name to 20 Characters
  src/main/java/seedu/trackermon/model/tag/Tag.java
Labels: type.Bug, priority.Low

#265 Fix Trackermon shows accepting different cases same name shows as unique shows
  src/main/java/seedu/trackermon/model/show/Name.java
Labels: type.Task, type.Bug, priority.High

#263 Fix Find Rating to handle Special Characters
  src/main/java/seedu/trackermon/commons/core/Messages.java
  src/main/java/seedu/trackermon/logic/parser/FindCommandParser.java
Labels: type.Task, type.Bug, priority.High

#274 Update Storage Test Cases
  src/main/java/seedu/trackermon/storage/JsonSerializableShowList.java
  src/main/java/seedu/trackermon/storage/StorageManager.java
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/data/JsonSerializableShowListTest/duplicateShowShowList.json
  src/test/data/JsonSerializableShowListTest/invalidShowShowList.json
  src/test/data/JsonSerializableShowListTest/typicalShowsShowList.json
  src/test/data/JsonShowListStorageTest/invalidAndValidShowShowList.json
  src/test/data/JsonShowListStorageTest/invalidShowShowList.json
  src/test/data/JsonShowListStorageTest/notJsonFormatShowList.json
  src/test/java/seedu/trackermon/storage/JsonAddressBookStorageTest.java
  src/test/java/seedu/trackermon/storage/JsonSerializableAddressBookTest.java
  src/test/java/seedu/trackermon/storage/JsonSerializableShowListTest.java
  src/test/java/seedu/trackermon/storage/JsonShowListStorageTest.java
  src/test/java/seedu/trackermon/storage/JsonUserPrefsStorageTest.java
  src/test/java/seedu/trackermon/storage/StorageManagerTest.java
  src/test/java/seedu/trackermon/testutil/ShowBuilder.java
  src/test/java/seedu/trackermon/testutil/TypicalShows.java
Labels: type.Task, priority.High

#275 Update test cases for Sort and Clear
  src/main/java/seedu/trackermon/logic/commands/SortCommand.java
  src/main/java/seedu/trackermon/logic/parser/SortCommandParser.java
  src/main/java/seedu/trackermon/model/show/NameComparator.java
  src/main/java/seedu/trackermon/model/show/RatingComparator.java
  src/main/java/seedu/trackermon/model/show/StatusComparator.java
  src/main/java/seedu/trackermon/model/show/TagComparator.java
  src/test/java/seedu/trackermon/logic/commands/ClearCommandTest.java
  src/test/java/seedu/trackermon/logic/commands/SortCommandTest.java
  src/test/java/seedu/trackermon/logic/parser/SortCommandParserTest.java
Labels: type.Task, priority.High, severity.High

#276 Update icon
  src/main/resources/images/trackermon_icon.png
Labels: type.Task, priority.High, severity.High

#270 Update DG (Suggest Command)
  docs/DeveloperGuide.md
Labels: type.Task

#277 Standardise error messages used across Trackermon
  src/main/java/seedu/trackermon/commons/core/Messages.java
  src/main/java/seedu/trackermon/logic/commands/AddCommand.java
  src/main/java/seedu/trackermon/logic/commands/CommentCommand.java
  src/main/java/seedu/trackermon/logic/commands/DeleteCommand.java
  src/main/java/seedu/trackermon/logic/commands/EditCommand.java
  src/main/java/seedu/trackermon/logic/commands/FindCommand.java
  src/main/java/seedu/trackermon/logic/commands/HelpCommand.java
  src/main/java/seedu/trackermon/logic/commands/SortCommand.java
  src/main/java/seedu/trackermon/logic/commands/SuggestCommand.java
  src/main/java/seedu/trackermon/logic/parser/CommentCommandParser.java
  src/main/java/seedu/trackermon/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/trackermon/logic/parser/EditCommandParser.java
  src/main/java/seedu/trackermon/logic/parser/FindCommandParser.java
  src/main/java/seedu/trackermon/logic/parser/ParserUtil.java
  src/main/java/seedu/trackermon/logic/parser/SortCommandParser.java
  src/main/java/seedu/trackermon/logic/parser/TrackermonParser.java
  src/main/java/seedu/trackermon/model/show/Name.java
  src/main/java/seedu/trackermon/model/show/Show.java
  src/main/java/seedu/trackermon/model/show/Status.java
  src/main/java/seedu/trackermon/model/tag/Tag.java
  src/main/java/seedu/trackermon/ui/ShowCard.java
  src/main/java/seedu/trackermon/ui/ShowDetailsCard.java
  src/test/java/seedu/trackermon/logic/LogicManagerTest.java
  src/test/java/seedu/trackermon/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/trackermon/logic/commands/AddCommandTest.java
  src/test/java/seedu/trackermon/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/trackermon/logic/commands/EditCommandTest.java
  src/test/java/seedu/trackermon/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/trackermon/logic/parser/DeleteCommandParserTest.java
  src/test/java/seedu/trackermon/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/trackermon/logic/parser/ParserUtilTest.java
  src/test/java/seedu/trackermon/logic/parser/SortCommandParserTest.java
  src/test/java/seedu/trackermon/logic/parser/TrackermonParserTest.java
  src/test/java/seedu/trackermon/model/show/ShowTest.java
  src/test/java/seedu/trackermon/testutil/AddressBookBuilder.java
  src/test/java/seedu/trackermon/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/trackermon/testutil/PersonBuilder.java
  src/test/java/seedu/trackermon/testutil/PersonUtil.java
  src/test/java/seedu/trackermon/testutil/TypicalPersons.java
Labels: type.Task, priority.High

#285 Add back JsonUtilTest tests
  src/test/java/seedu/trackermon/commons/util/JsonUtilTest.java
Labels: type.Task, priority.High

#278 Bug Fix for sort UG
  docs/UserGuide.md
Labels: type.Bug, priority.High, severity.High

#281 Remove unused class
  src/main/java/seedu/trackermon/model/show/exceptions/RatingNotValidException.java
  src/test/java/seedu/trackermon/logic/commands/TempCommandTestUtil.java
  src/test/java/seedu/trackermon/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/trackermon/model/AddressBookTest.java
  src/test/java/seedu/trackermon/model/person/AddressTest.java
  src/test/java/seedu/trackermon/model/person/EmailTest.java
  src/test/java/seedu/trackermon/model/person/NameTest.java
  src/test/java/seedu/trackermon/model/person/PersonTest.java
  src/test/java/seedu/trackermon/model/person/PhoneTest.java
  src/test/java/seedu/trackermon/model/person/UniquePersonListTest.java
Labels: type.Task, priority.High, severity.High

#284 Add test cases that is left commented out
  src/main/java/seedu/trackermon/model/tag/Tag.java
  src/test/java/seedu/trackermon/model/ModelManagerTest.java
  src/test/java/seedu/trackermon/model/UserPrefsTest.java
  src/test/java/seedu/trackermon/model/util/SampleDataUtilTest.java
  src/test/java/seedu/trackermon/testutil/ShowListBuilder.java
Labels: type.Task, priority.High

#292 Update PPP
  docs/team/ardentsoul.md
Labels: type.Task, priority.High

#288 Add header comments to Logic Test
  src/test/java/seedu/trackermon/logic/LogicManagerTest.java
  src/test/java/seedu/trackermon/logic/commands/AddCommandTest.java
  src/test/java/seedu/trackermon/logic/commands/ClearCommandTest.java
  src/test/java/seedu/trackermon/logic/commands/CommandResultTest.java
  src/test/java/seedu/trackermon/logic/commands/EditShowDescriptorTest.java
  src/test/java/seedu/trackermon/logic/commands/ExitCommandTest.java
  src/test/java/seedu/trackermon/logic/commands/HelpCommandTest.java
  src/test/java/seedu/trackermon/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/trackermon/logic/parser/ArgumentTokenizerTest.java
  src/test/java/seedu/trackermon/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/trackermon/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/trackermon/logic/parser/ParserUtilTest.java
  src/test/java/seedu/trackermon/logic/parser/SortCommandParserTest.java
  src/test/java/seedu/trackermon/logic/parser/TrackermonParserTest.java
Labels: type.Task, priority.High, severity.High

#286 Update Testing for Trackermon
  src/test/java/seedu/trackermon/model/ShowListTest.java
  src/test/java/seedu/trackermon/model/show/CommentTest.java
  src/test/java/seedu/trackermon/model/show/RatingTest.java
  src/test/java/seedu/trackermon/model/tag/TagTest.java
Labels: priority.Low

#293 Update Sort Images to be consistent
  docs/images/Sort_UI.png
  docs/images/Sort_UI2.png
  docs/images/Sort_UI3.png
  docs/team/ardentsoul.md
Labels: type.Task, priority.High

#297 Update PPP
  docs/team/arcornior.md
Labels: type.Task, priority.High

#296 Update index UI.png and PPP
  docs/images/AB3-Ui.png
  docs/images/Ui.png
  docs/team/jonathanhoshi.md
Labels: type.Task, priority.High

#300 Update PPP (aweijun)
  docs/team/aweijun.md
Labels: type.Task, priority.High

#301 Update PPP
  docs/team/ardentsoul.md
Labels: type.Task, priority.High

#303 Update Javadocs for main logic
  src/main/java/seedu/trackermon/logic/LogicManager.java
  src/main/java/seedu/trackermon/logic/commands/AddCommand.java
  src/main/java/seedu/trackermon/logic/commands/ClearCommand.java
  src/main/java/seedu/trackermon/logic/commands/Command.java
  src/main/java/seedu/trackermon/logic/commands/DeleteCommand.java
  src/main/java/seedu/trackermon/logic/commands/EditCommand.java
  src/main/java/seedu/trackermon/logic/commands/ExitCommand.java
  src/main/java/seedu/trackermon/logic/commands/ExportCommand.java
  src/main/java/seedu/trackermon/logic/commands/FindCommand.java
  src/main/java/seedu/trackermon/logic/commands/HelpCommand.java
  src/main/java/seedu/trackermon/logic/commands/ImportCommand.java
  src/main/java/seedu/trackermon/logic/commands/ListCommand.java
  src/main/java/seedu/trackermon/logic/commands/SortCommand.java
  src/main/java/seedu/trackermon/logic/commands/SuggestCommand.java
  src/main/java/seedu/trackermon/logic/commands/exceptions/CommandException.java
  src/main/java/seedu/trackermon/logic/parser/AddCommandParser.java
  src/main/java/seedu/trackermon/logic/parser/ArgumentMultimap.java
  src/main/java/seedu/trackermon/logic/parser/ArgumentTokenizer.java
  src/main/java/seedu/trackermon/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/trackermon/logic/parser/EditCommandParser.java
  src/main/java/seedu/trackermon/logic/parser/FindCommandParser.java
  src/main/java/seedu/trackermon/logic/parser/Parser.java
  src/main/java/seedu/trackermon/logic/parser/ParserUtil.java
  src/main/java/seedu/trackermon/logic/parser/Prefix.java
  src/main/java/seedu/trackermon/logic/parser/SortCommandParser.java
  src/main/java/seedu/trackermon/logic/parser/TrackermonParser.java
  src/main/java/seedu/trackermon/logic/parser/exceptions/ParseException.java
  src/main/java/seedu/trackermon/model/show/NameContainsKeywordsPredicate.java
  src/main/java/seedu/trackermon/model/show/RatingContainsKeywordsPredicate.java
  src/main/java/seedu/trackermon/model/show/ShowContainsKeywordsPredicate.java
  src/main/java/seedu/trackermon/model/show/StatusContainsKeywordsPredicate.java
  src/main/java/seedu/trackermon/model/show/TagsContainsKeywordsPredicate.java
Labels: type.Task, priority.High

#299 Update code quality of all commons and ui classes/methods
  src/main/java/seedu/trackermon/AppParameters.java
  src/main/java/seedu/trackermon/Main.java
  src/main/java/seedu/trackermon/MainApp.java
  src/main/java/seedu/trackermon/commons/core/Config.java
  src/main/java/seedu/trackermon/commons/core/GuiSettings.java
  src/main/java/seedu/trackermon/commons/core/JarTools.java
  src/main/java/seedu/trackermon/commons/core/LogsCenter.java
  src/main/java/seedu/trackermon/commons/core/Version.java
  src/main/java/seedu/trackermon/commons/core/index/Index.java
  src/main/java/seedu/trackermon/commons/exceptions/DataConversionException.java
  src/main/java/seedu/trackermon/commons/exceptions/IllegalValueException.java
  src/main/java/seedu/trackermon/commons/util/ConfigUtil.java
  src/main/java/seedu/trackermon/logic/commands/CommandResult.java
  src/main/java/seedu/trackermon/storage/JsonFileManager.java
  src/main/java/seedu/trackermon/ui/CommandBuilder.java
  src/main/java/seedu/trackermon/ui/HelpWindow.java
  src/main/java/seedu/trackermon/ui/ResultDisplay.java
  src/main/java/seedu/trackermon/ui/ShowCard.java
  src/main/java/seedu/trackermon/ui/Ui.java
  src/main/java/seedu/trackermon/ui/UiManager.java
  src/test/java/seedu/trackermon/commons/core/ConfigTest.java
  src/test/java/seedu/trackermon/commons/core/GuiSettingsTest.java
  src/test/java/seedu/trackermon/commons/core/JarToolsTest.java
  src/test/java/seedu/trackermon/commons/core/VersionTest.java
  src/test/java/seedu/trackermon/commons/core/index/IndexTest.java
  src/test/java/seedu/trackermon/commons/exceptions/IllegalValueExceptionTest.java
  src/test/java/seedu/trackermon/commons/util/AppUtilTest.java
  src/test/java/seedu/trackermon/commons/util/CollectionUtilTest.java
  src/test/java/seedu/trackermon/commons/util/ConfigUtilTest.java
  src/test/java/seedu/trackermon/commons/util/FileUtilTest.java
  src/test/java/seedu/trackermon/commons/util/JsonUtilTest.java
  src/test/java/seedu/trackermon/commons/util/StringUtilTest.java
  src/test/java/seedu/trackermon/model/ModelManagerTest.java
  src/test/java/seedu/trackermon/model/UserPrefsTest.java
  src/test/java/seedu/trackermon/ui/CommandBuilderTest.java
  src/test/java/seedu/trackermon/ui/UiPartTest.java
Labels: type.Task, priority.High

#298 Add Javadoc header for Storage test classes
  src/test/java/seedu/trackermon/storage/JsonSerializableShowListTest.java
  src/test/java/seedu/trackermon/storage/JsonShowListStorageTest.java
  src/test/java/seedu/trackermon/storage/JsonUserPrefsStorageTest.java
  src/test/java/seedu/trackermon/storage/StorageManagerTest.java
Labels: type.Task, priority.High

#308 Add Code Reuse
  docs/DeveloperGuide.md
  src/main/java/seedu/trackermon/logic/parser/FindCommandParser.java
  src/main/java/seedu/trackermon/ui/HelpWindow.java
Labels: type.Task, priority.High

#290 Add more test cases for predicates
  src/test/java/seedu/trackermon/logic/commands/FindCommandTest.java
  src/test/java/seedu/trackermon/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/trackermon/model/person/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/trackermon/model/show/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/trackermon/model/show/RatingContainsKeywordsPredicateTest.java
  src/test/java/seedu/trackermon/model/show/ShowContainsKeywordsPredicateTest.java
  src/test/java/seedu/trackermon/model/show/StatusContainsKeywordsPredicateTest.java
  src/test/java/seedu/trackermon/model/show/TagsContainsKeywordsPredicateTest.java
Labels: type.Task, priority.High

#307 Update copyright and reuse policy information
  copyright.txt
  src/main/java/seedu/trackermon/commons/core/JarTools.java
Labels: type.Task, priority.High

#310 Update Java Docs (Model) + Minor Refractor (Name)
  src/main/java/seedu/trackermon/model/ShowList.java
  src/main/java/seedu/trackermon/model/show/Comment.java
  src/main/java/seedu/trackermon/model/show/Name.java
  src/main/java/seedu/trackermon/model/show/NameContainsKeywordsPredicate.java
  src/main/java/seedu/trackermon/model/show/Rating.java
  src/main/java/seedu/trackermon/model/show/Show.java
  src/main/java/seedu/trackermon/model/show/ShowContainsKeywordsPredicate.java
  src/main/java/seedu/trackermon/model/show/Status.java
  src/main/java/seedu/trackermon/model/show/SuggestPredicate.java
  src/main/java/seedu/trackermon/model/show/UniqueShowList.java
  src/main/java/seedu/trackermon/model/show/exceptions/DuplicatedShowException.java
  src/main/java/seedu/trackermon/model/show/exceptions/ShowNotFoundException.java
  src/main/java/seedu/trackermon/model/tag/Tag.java
  src/main/java/seedu/trackermon/storage/JsonAdaptedShow.java
  src/main/java/seedu/trackermon/ui/ShowCard.java
  src/main/java/seedu/trackermon/ui/ShowDetailsCard.java
  src/test/java/seedu/trackermon/logic/commands/CommandTestUtil.java
  src/test/java/seedu/trackermon/model/ModelManagerTest.java
  src/test/java/seedu/trackermon/model/show/NameTest.java
  src/test/java/seedu/trackermon/testutil/ShowUtil.java
  src/test/java/seedu/trackermon/testutil/TypicalShows.java
Labels: priority.Medium

#305 Limit Comment to 300000 Chars
  docs/UserGuide.md
  src/main/java/seedu/trackermon/logic/parser/ParserUtil.java
  src/main/java/seedu/trackermon/model/show/Comment.java
  src/test/java/seedu/trackermon/model/show/CommentTest.java
Labels: type.Task, priority.High

#304 Update PPP to fix formatting and Add more information
  docs/team/jonathanhoshi.md
Labels: type.Task, priority.High

#315 Limit Name + Minor refractor(Rating)
  docs/UserGuide.md
  src/main/java/seedu/trackermon/logic/parser/FindCommandParser.java
  src/main/java/seedu/trackermon/logic/parser/ParserUtil.java
  src/main/java/seedu/trackermon/model/show/Name.java
  src/main/java/seedu/trackermon/model/show/Rating.java
  src/main/java/seedu/trackermon/storage/JsonAdaptedShow.java
  src/test/java/seedu/trackermon/model/show/NameTest.java
  src/test/java/seedu/trackermon/model/show/RatingTest.java
Labels: type.Bug, priority.High, severity.Low

#313 Update DG to contain rating
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/images/BetterModelClassDiagram.png
  docs/images/ModelClassDiagram.png
Labels: priority.Medium

#311 Update JavaDocs (Test)
  src/test/java/seedu/trackermon/model/show/CommentTest.java
  src/test/java/seedu/trackermon/model/show/NameTest.java
  src/test/java/seedu/trackermon/model/show/RatingTest.java
  src/test/java/seedu/trackermon/model/show/ShowTest.java
  src/test/java/seedu/trackermon/model/tag/TagTest.java
Labels: priority.High

#317 Update UG
  docs/UserGuide.md
  src/main/java/seedu/trackermon/ui/HelpWindow.java
Labels: type.Task, priority.High

#316 Update Help Window
  docs/images/HelpWindow.png
Labels: type.Task, priority.High

#318 Update PPP
  docs/team/aweijun.md
Labels: priority.High, severity.VeryLow

#320 Edit PPP
  docs/team/arcornior.md
  docs/team/ardentsoul.md
  docs/team/jonathanhoshi.md
Labels: type.Task, priority.High

#319 DG UG final changes
  docs/DeveloperGuide.md
  docs/SettingUp.md
  docs/UserGuide.md
Labels: type.Task, priority.High

#322 Update About Us Image
  docs/images/ardentsoul.png
Labels: type.Task, priority.High

#323 Refractoring (Code Quality)
  docs/DeveloperGuide.md
  src/main/java/seedu/trackermon/logic/commands/SuggestCommand.java
  src/main/java/seedu/trackermon/model/ShowList.java
  src/main/java/seedu/trackermon/model/show/Comment.java
  src/main/java/seedu/trackermon/model/show/SameShowPredicate.java
Labels: priority.Medium, severity.Low

#324 Javac Docs and Delete Unused Methods
  src/main/java/seedu/trackermon/logic/commands/SuggestCommand.java
  src/main/java/seedu/trackermon/model/show/Comment.java
  src/main/java/seedu/trackermon/model/show/Name.java
  src/main/java/seedu/trackermon/model/show/Rating.java
  src/main/java/seedu/trackermon/model/show/Show.java
  src/main/java/seedu/trackermon/model/show/Status.java
  src/main/java/seedu/trackermon/model/show/UniqueShowList.java
Labels: priority.Medium, severity.Low

#328 Fix Links
  docs/team/aweijun.md
Labels: priority.Medium, severity.Low

#327 Update version number of Trackermon
  src/main/java/seedu/trackermon/MainApp.java
Labels: type.Task, priority.High
